
embed_assets: on
package_assets: allways

javascripts:
  workspace:
    - public/javascripts/application.js
    - public/javascripts/*.js

stylesheets:
  common:
    - public/stylesheets/application.css
    - public/stylesheets/*.css
  workspace:
  #  - public/stylesheets/pages/workspace.css
  empty:
  #  - public/stylesheets/pages/empty.css